server:
  port: 9090

spring:
  datasource:
    username: root
    password: km1234
    url: jdbc:mariadb://localhost:3306/kmportfolio?characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false


