server:
  port: 9090

spring:
  datasource:
    username: root
    password: km1234
    url: jdbc:mariadb://localhost:3306/kmportfolio?characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
  mail:
    host: smtp.gmail.com
    port: 587
    username: 119lenagend119@gmail.com
    password: point-good713
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  devtools:
    livereload:
      enabled: true
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true


